In [56]:
import pandas as pd
import numpy as np
export = pd.DataFrame({'International':['cocoa butter', 'liquor', 'cake', ''],
                         'Locally':['cocoa powder', '', '', '']
                    })

segments = pd.DataFrame({'Refreshment Beverages':['Bournvita','Hot Chocolate', '', ''],
                    "Confectionery":['Tom Tom', 'Buttermint', '', ''],
                    'Intermadiate Cocoa Products':['cocoa powder','cocoa butter', 'cocoa liquor', 'cocoa cake']
                    })
brands = pd.DataFrame({'Refreshment Beverages':['Cadbury Bournvita','Cadbury 3-in-1 Hot Chocolate', '', ''],
                     "Confectionery":['Tom Tom Classic', 'Tom Tom Buttermint', 'Tom Tom Strawberry', ''],
                    'Intermadiate Cocoa Products':['cocoa powder','cocoa butter', '', '']
                   })
arr = pd.concat([export, brands, segments],keys =('Refreshment Beverages',"Confectionery",'Intermadiate Cocoa Products',
                                                  "export"))
arr
#segments
#brands

                              International       Locally  \
Refreshment Beverages       0  cocoa butter  cocoa powder
                            1        liquor
                            2          cake
                            3
Confectionery               0           NaN           NaN
                            1           NaN           NaN
                            2           NaN           NaN
                            3           NaN           NaN
Intermadiate Cocoa Products 0           NaN           NaN
                            1           NaN           NaN
                            2           NaN           NaN
                            3           NaN           NaN

                                      Refreshment Beverages  \
Refreshment Beverages       0                           NaN
                            1                           NaN
                            2                           NaN
                            3                           NaN
Confectionery               0             Cadbury Bournvita
                            1  Cadbury 3-in-1 Hot Chocolate
                            2
                            3
Intermadiate Cocoa Products 0                     Bournvita
                            1                 Hot Chocolate
                            2
                            3

                                    Confectionery Intermadiate Cocoa Products
Refreshment Beverages       0                 NaN                         NaN
                            1                 NaN                         NaN
                            2                 NaN                         NaN
                            3                 NaN                         NaN
Confectionery               0     Tom Tom Classic                cocoa powder
                            1  Tom Tom Buttermint                cocoa butter
                            2  Tom Tom Strawberry
                            3
Intermadiate Cocoa Products 0             Tom Tom                cocoa powder
                            1          Buttermint                cocoa butter
                            2                                    cocoa liquor
                            3                                      cocoa cake